- src/lib.rs
- src/scope_manager.rs
- src/vm_core.rs
- Add `PyEnterScope` and `PyExitScope`, each with its `__call__ `pymethod and update_scopes method
- Integrate them into `execute_hint`
- Add tests
Depends on #10
> Add support for vm_enter_scope and vm_exit_scope

- cairo_programs/array_sum.cairo
- cairo_programs/array_sum.json
- cairo_programs/fibonacci.cairo
- cairo_programs/fibonacci.json
- cairo_programs/hint_print_vars.cairo
- cairo_programs/hint_print_vars.json
- src/cairo_run.rs
- src/ids.rs
- src/lib.rs
- src/memory.rs
- src/vm_core.rs
This PR adds the implementation of cairo_run for this crate, namely `cairo_run_py`. 
It depends on the cairo-rs PR:
https://github.com/lambdaclass/cairo-rs/pull/475
The structure of the function is very similar to `cairo_run` from cairo-rs, with some little changes so that it fits properly into this scheme.
A function `run_until_pc` analogous to the CairoRunner's method from cairo-rs was implemented, that receives the CairoRunner as an argument.
NOTE: In contrast to `cairo_run`, `cairo_run_py` initializes the hint processor instead of receiving it as an argument. The implementation was much simpler this way, and for the moment I don't think a custom hint processor will be needed, but this could be changed in the future. Another difference is that the trace file and memory file are passed …
> Add implementation of cairo_run

- src/cairo_run.rs
- src/ids.rs
- src/relocatable.rs
- src/scope_manager.rs
- src/vm_core.rs
Add support for hint_locals
hint_locals is a dictionary of python objects that can be accessed and modified by any hint regardless of scopes
> Add support for hint_locals

- src/relocatable.rs
Remove unused methods `to_maybe_relocatable() `and `to_relocatable()` from `PyMaybeRelocatable`, as there are already From implementations for these conversions.
> Remove unused conversion methods

- src/relocatable.rs
- src/scope_manager.rs
- src/vm_core.rs
Solves #27.
This PR fixes the crate to be compatible with the changes made to `cairo-rs`:
* `PyRelocatable` has a segment index of type `isize`, analogous to the `Relocatable` struct of `cairo-rs`.
* `ExecScopesProxy` has been replaced to `ExecScopes`
> Fix PyRelocatable index and remove ExecScopesProxy

- src/vm_core.rs
This PR adds Python builtins import so that the module `cairo_rs_py` can run with any Python version.
Without this, Python 3.10+ are the only ones that can use the module correctly.
> Import Python builtins in execute_hint function

- src/relocatable.rs
- src/vm_core.rs
Change field name from `index `to `segment_index` to match python type
Expose segment_index and offset through `#[pyo3(get)]`
Add unit test for this case
> Fix name and expose atributes of Relocatable

- Cargo.toml
This fixes the cairo-rs version used to a272cd to allow decoupling changes between the projects and avoid stuff breaking behind cairo-rs-py's back.
> Point cairo-rs to rev a272cd

- src/vm_core.rs
Motivation: A bug was found when using list comprehension inside hints. When a local dictionary is used, variables created inside the hint are stored in locals, but list comprehension looks for variables in locals, leading to undefined name errors. In order to fix this, the local dictionary was removed so that every variable would be stored and fetched from globals
- Move executions scope and hint_local variables to global dictionary
- Remove local dictionary
- Add test for hint using list comprehension
> Move execution scope and hint_local variables to globals

- src/vm_core.rs
Adds the following tests:
`enter_exit_scope_separate_hints`
`enter_exit_enter_scope_same_hint`
> Add more tests for vm_enter_scope and vm_exit_scope interaction

- Makefile
Remove duplicate targets `run-python-tests-macos `and `full-test-macos` which do the same as `run-python-tests` and `full-test`
> Remove duplicate targets from Makefile

- Cargo.toml
- hints_tests.py
- src/ids.rs
This PR adds support for assigning PyTypeIds fields. This is useful when assigning struct fields inside a hint.
It also corrects the `__getattr__` method.
With this fixes, the following tests run:
* pow
* compute_slope
* ec_double
* uint256_unsigned_div_rem
* uint256_sqrt
**Note**: If a field inside a struct is another struct and we want to assign a struct there, it would fail. It is not clear at the moment if this should be supported. See issue #86.
> Add setattr and fix getattr to PyTypeId struct

- Cargo.toml
- src/cairo_runner.rs
this PR depends on https://github.com/lambdaclass/cairo-rs/pull/545 to work, since that PR exposes the required method in VM core
> Expose get_segment_used_size in cairo runner

- src/memory_segments.rs
This PR depends on https://github.com/lambdaclass/cairo-rs/pull/556, that exposes the required method from memory_segments.rs
> Expose function add_memory_segment in SegmentManager

- Cargo.toml
- src/cairo_runner.rs
This PR adds the `PyCairoRunner::initialize_function_runner()` method.
> Initialize function runner py cairo runner

- Cargo.toml
- src/cairo_runner.rs
This PR refactors `run_from_entrypoint`. At the moment this method internally called `cairo-rs`'s `run_from_entrypoint`, which resulted in an `UnknownHintError` when executing the function in the StarkNet environment.
Depends on https://github.com/lambdaclass/cairo-rs/pull/595
> Refactor run_from_entrypoint()

- Cargo.toml
- get_builtins_initial_stack.py
- src/cairo_runner.rs
This PR filter the initial stacks we return because we only need the ones contained in the program builtins.
> Return only program builtins

- get_builtins_initial_stack.py
- src/cairo_runner.rs
Change PyCairoRunner::get_program_builtins_initial_stack() to return Vec<PyMaybeRelocatable> instead of Vec<Vec<PyMaybeRelocatable>>
> Fix output of PyCairoRunner::get_program_builtins_initial_stack()

- Cargo.toml
- cairo_programs/relocate_segments.cairo
- cairo_programs/relocate_segments_with_offset.cairo
- hints_tests.py
- src/cairo_runner.rs
- src/memory.rs
- src/memory_segments.rs
* Add `Memory.memory.add_relocation_rule()` method
* Add integration test
* Add `end_run` in `fn cairo_run_py`
> Add relocation rule method and `end_run` in `fn cairo_run_py`

- .gitignore
- Cargo.toml
- scripts/README.md
- scripts/build_envs.sh
- scripts/move-to-cairo-rs-py.patch
The scripts does the following:
- Install two venvs, `cairo-rs-py` and `cairo-lang`;
- Install `cairo-lang` in both environments;
- In `cairo-rs-py` it installs `cairo-rs-py` and applies a patch implementing the changes we had to do to `cairo-lang` to run with our VM in the installed package;
- Runs `starknet --version` and `cairo-run --version` in the `cairo-rs-py` venv to confirm it's using our VM.
Remaining work: a little README explaining the usage.
> Implement quick and dirty script for setting venvs to compare cairo-lang with cairo-rs-py

- src/ids.rs
Previously PyIds passed the pointer cairo type to PyTypedId, causing a "Failed to get struct type" error. This PR also adds a unit test for that case.
> Change PyIds handling of pointer types

- src/cairo_runner.rs
This PR should allow using `runner.memory.<attr-or-method>`-style calls from Python (as in the reference implementation).
> Implement `CairoRunner::memory` proxy.

- src/cairo_runner.rs
- src/ids.rs
- src/memory.rs
- src/scope_manager.rs
- src/utils.rs
- src/vm_core.rs
* Modify VmCore::step to return a PyErr instead of a VirtualMachineError
* Remove unused fn Utils::to_vm_error
> Modify VmCore::step to return a PyErr

- README.md
- scripts/build_envs.sh
Upgraded the cairo-lang version to 0.10.3 to match the sequencer address of the tests in the devnet.
> Update to new version of cairo-lang

- Cargo.toml
- Makefile
- src/lib.rs
Building `cairo-rs-py` as library requires __not__ linking to the CPython library. This is achieved by making the default build pass the `extension-module` feature flag to PyO3 and making it exclusive with `auto-initialize`.
When testing we do need this to initialize the CPython machine, so it's a different feature that the `make` target passes to Cargo.
> Fix `maturin build`

- src/cairo_runner.rs
- src/ecdsa.rs
- src/lib.rs
- src/vm_core.rs
This PR:
- adds more unit tests to `cairo_runner.rs`
- removes the warning (_warning: use of deprecated trait `pyo3::PyIterProtocol`: prefer `#[pymethods]` to `#[pyproto]`_) that occurs when compiling them
- moves the declaration of some test Python Objects to a test submodule
> Add unit tests to cairo_runner

- Cargo.lock
- Cargo.toml
- src/cairo_runner.rs
- src/ecdsa.rs
- src/ids.rs
- src/instruction_location.rs
- src/memory.rs
- src/memory_segments.rs
- src/range_check.rs
- src/relocatable.rs
- src/run_context.rs
- src/scope_manager.rs
- src/to_felt_or_relocatable.rs
- src/utils.rs
- src/vm_core.rs
Updates cairo-rs version to match the current last commit in cairo-rs
Most notable changes in cairo-rs:
- new error type HintError
- new type Felt
- cairo-rs crate name changed to cairo-vm
Other changes in cairo-rs-py:
- Swap BigInt for BigUint
> Update cairo-rs version to last commit in main (last PR merged: #742)

- Cargo.lock
- Cargo.toml
- src/cairo_runner.rs
- src/ecdsa.rs
- src/ids.rs
- src/memory.rs
- src/memory_segments.rs
- src/range_check.rs
- src/relocatable.rs
- src/utils.rs
- src/vm_core.rs
Depends on https://github.com/lambdaclass/cairo-rs/pull/780
- Remove now-impossible test case
- Add `verify_secure_runner` call to `cairo_run_py` (This solves Issue #216) 
Note: The test I removed only fails when `SignatureBuiltinRunner::add_signature` fails to convert a Felt into a FieldElement. This used to happen when the Felt was equal to cairo's prime. This no longer happens as Felt::from now returns Felt::zero when the value is equal to CAIRO_PRIME (PR https://github.com/lambdaclass/cairo-rs/pull/743)
> Update cairo-rs version after `BuiltinRunner::final_stack` fix

- Makefile
Without export it does not manage to set the environment variable correctly.
> Fix env variable in hyperfine command

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/cairo_runner.rs
- src/ecdsa.rs
- src/ids.rs
- src/memory_segments.rs
- src/utils.rs
- src/vm_core.rs
This PR bumps the _cairo-vm_ version to latest. In the process, rust toolchain version in the CI was bumped to `1.69` (same as the vm's).
Also added `--all-targets` flag to clippy.
> chore: bump _cairo-vm_ version
