src/scope_manager.rs, src/vm_core.rs
This reverts commit 0522dae50d901a62d35c8dc4f04063f1e6a5bdb3.
=> Revert "Change num in PyExitScope type to u32"

src/scope_manager.rs, src/vm_core.rs
=> Change num in PyExitScope type to u32

cairo_programs/assert_nn_hint.cairo, src/lib.rs, src/range_check.rs, src/vm_core.rs
Adds the RangeCheck object in the python console, with the `bound` attribute. 
Adds the PRIME const in python console.
Adds a test program to test this new object.
=> Add py range check

src/cairo_run.rs, src/lib.rs, src/vm_core.rs
=> Move cairo_run method to PyVm

Cargo.toml, src/vm_core.rs
Update  cairo-rs version to last commit in Cargo.toml
=> Update cairo-rs version

Makefile
This reverts commit 54dbbcad3f67529ee8629b816cde9dc5cdb91add.
=> Revert "Add makefile"

Cargo.toml, src/cairo_runner.rs, src/ids.rs, src/vm_core.rs
Depends on [this PR](https://github.com/lambdaclass/cairo-rs/pull/514) on `cairo-rs`.
=> Remove `.unwrap()` from cairo struct implementation.

Cargo.toml, cairo_programs/ids_size.cairo, hints_tests.py, src/cairo_runner.rs, src/ids.rs
Update cairo-rs commit
Fix fn CairoRunner.get_output
Add Ids.Struct.SIZE to PyIds
Fix dict_read.cairo and dict_update.cairo test
=> Add ids.Struct_definition 

cairo_programs/ec_negate.cairo, hints_tests.py
Waiting for https://trello.com/c/y1J9iHZ2/42-fix-computeslopecairo-ecdoublecairo
=> Fix ec_negate.cairo test

Cargo.toml, hints_tests.py, src/cairo_run.rs, src/cairo_runner.rs, src/ids.rs, src/memory_segments.rs
Fixed compatibility issues with PR 506 in cairo-rs
TODO: change Cargo.toml once PR is merged
=> Fix compatibility once layouts PR is merged in cairo-rs

Cargo.toml, hints_tests.py, src/memory.rs, src/vm_core.rs
this pull request depends on this one:
https://github.com/lambdaclass/cairo-rs/pull/529
Which implements inside VmCore the function required to map rust types to python types.
=> Get range method

Makefile, cairo_programs/get_builtins_initial_stack.cairo, get_builtins_initial_stack.py, src/cairo_runner.rs, src/relocatable.rs
This PR adds:
- CairoRunner::runner.get_builtins_initial_stack()
- CairoRunner::add_segment()
https://trello.com/c/qjHkEx3h/49-prepareoscontext
=> prepare_os_context util functions

Cargo.toml, cairo_programs/final_stack.cairo, src/cairo_runner.rs
This PR requires this one : https://github.com/lambdaclass/cairo-rs/pull/574  to properly work.
=> Implement get_builtint_final_stack

src/cairo_runner.rs
Instead of exposing and using memory segment manager in StarkNet code like
```
segments = runner.segments
segments.write_arg(...)
```
we decided to add those methods to the runner. In this way we can use directly
```
runner.write_arg(...)
```
The methods were copied from the implementation of `PySegmentManager`
=> Add write_arg and gen_arg to CairoRunner

src/range_check.rs
=> Add unit tests in range_check.rs

src/relocatable.rs
Add unit tests for `relocatable.rs`.
=> Test relocatable.rs

Cargo.toml, src/cairo_runner.rs
Depends on https://github.com/lambdaclass/cairo-rs/pull/601
=> Change builtin instance counter type

Cargo.toml, src/cairo_runner.rs, src/ids.rs, src/memory.rs, src/memory_segments.rs, src/range_check.rs, src/relocatable.rs, src/vm_core.rs
Depends on [cairo-rs#605](https://github.com/lambdaclass/cairo-rs/pull/605).
=> Implement pycairorunner get range

src/cairo_runner.rs
- Reverse iterator in get_builtins_final_stack
- Add test for this case
- Add test to check that get_program_builtins_initial_stack is not reversed
=> Reverse iterator in get_builtins_final_stack

src/cairo_runner.rs
https://trello.com/c/4g0p2eeW/38-cambiar-inicialización-de-pycairorunner
=> Remove hardcoded prime from VM in CairoRunner::new()

Cargo.toml, src/cairo_runner.rs, src/ids.rs, src/memory.rs, src/memory_segments.rs, src/vm_core.rs
=> Fix stuff that would break after merging cairo-rs #609.

src/dict_manager.rs
This PR adds unit tests for PyDictManager and PyDictTracker, implemented on #118
=> Add unit tests for Dict manager

src/dict_manager.rs
This PR adds more unit tests for PyDictManager and PyDictTracker, implemented on #118
=> Add tests for the failing cases of PyDictManager

README.md
This PR adds badges, a list of dependencies, and a basic project description to the main README.
=> Expand repository's README

src/cairo_runner.rs, src/ecdsa.rs, src/lib.rs
This PR add test to ecdsa.rs file
=> Cairo runner new unit tests

Cargo.lock, Cargo.toml, cairo_programs/double_value_offset.cairo, scripts/move-to-cairo-rs-py.patch, src/ids.rs, src/run_context.rs, src/vm_core.rs
=> Integrate Parser Refactor

Cargo.lock, Cargo.toml, src/cairo_runner.rs, src/instruction_location.rs, src/vm_core.rs
Depends on https://github.com/lambdaclass/cairo-rs/pull/673
=> Use hint_location upon hint failure

src/cairo_runner.rs
Import new type of error to match the python VM implementation
=> Import resources error from cairo lang

README.md
- standardized structure
- fixed and reconstructed table of contents
- added more shields
- added links to submit issues (request feature or report bug)
- made titles prettier
- minor fixes
=> overhaul README.md
